from .logging import setup_logging
from .models import (
    MODEL_EMBED,
    MODEL_FAST,
    MODEL_STANDARD,
    MODEL_VISION_FAST,
    MODEL_VISION_HEAVY,
    get_model,
)
from .paths import (
    BASE_DIR,
    DATA_DIR,
    EVAL_SET_PATH,
    KNOWLEDGE_GRAPH_DB_PATH,
    MODELS_DIR,
    QUEUE_STATUS_PATH,
    RERANKER_MODEL_PATH,
    TRAINING_DATA_DIR,
    TRAINING_PAIRS_PATH,
)
from .settings import (
    API_URL,
    CHROMA_HOST,
    CHROMA_PORT,
    CHUNK_OVERLAP,
    CHUNK_SIZE,
    HANDWRITTEN_IMAGE_THRESHOLD,
    HANDWRITTEN_TEXT_THRESHOLD,
    MAX_FINAL_RESULTS,
    MAX_RETRIEVAL_PASSES,
    OLLAMA_URL,
    REDIS_HOST,
    REDIS_PORT,
    RRF_K,
    TOP_K_CANDIDATES,
    VISION_TIMEOUT_SECONDS,
    WANDB_PROJECT,
)
